### ISSUE TITLE
Color escape sequences not Windows friendly.

### ISSUE THREAD

**Issue by ChrisHines** [shurcooL/binstale#10]
Consider using a package such as github.com/fatih/color to provide colors compatible with the Windows console.

**Comment by dmitshur** [comment]
Thanks for reporting this.

Is it a problem with the standard windows cmd.exe command prompt?

**Comment by ChrisHines** [comment]
Yes. I experienced the problem on Windows 10 with cmd.exe.

**Comment by dmitshur** [comment]
I looked at my use of colors in this tool and realized it's not a good idea. I took them out in cfe7dc1edfec4a1a1d63ae9ad597f5120d1af353. This issue should be resolved as a result.

**Comment by ChrisHines** [comment]
Yes, it is resolved. Thanks.
