### ISSUE TITLE
binstale reports stale fmt and bytes packages

### ISSUE THREAD

**Issue by bits01** [shurcooL/binstale#12]
```
Go-Package-Store
	stale: github.com/shurcooL/Go-Package-Store/cmd/Go-Package-Store (stale dependency: fmt)
binstale
	stale: github.com/shurcooL/binstale (stale dependency: fmt)
goimports
	stale: golang.org/x/tools/cmd/goimports (stale dependency: fmt)
govendor
	stale: github.com/kardianos/govendor (stale dependency: bytes)
...
```

Any ideas why? This is with go 1.10, not sure whether it has anything to do with the new build cache.

**Comment by dmitshur** [comment]
Yes, this is a known regression upstream in `cmd/go` in Go 1.10. It might get fixed in Go 1.10.1.

See https://github.com/golang/go/issues/23818 and https://github.com/golang/go/issues/23797.

Thanks for reporting this anyway.

**Comment by bits01** [comment]
Thank you, appreciate your prompt reply.

**Comment by dmitshur** [comment]
[Go 1.10.2](https://groups.google.com/forum/#!topic/golang-announce/qXEbop4t-Wg) has been released today, which resolves this issue. Please update to it and rebuild `binstale`.
