### ISSUE TITLE
Option to list only the stale/up to date packages

### ISSUE THREAD

**Issue by kulshekhar** [shurcooL/binstale#7]
In cases when there are a lot of binaries, the names of some of the stale binaries scroll out of view. While updating these, we have to scroll up, see the name, type it and repeat the process.

It would be very helpful if `binstale` had a flag that allowed the user to choose if they want to display stale or up to date packages (defaults to the current behaviour).

It would also be helpful to have the output take up just one line per binary, like so:

```
dlv (up to date): github.com/derekparker/delve/cmd/dlv
```

or 

```
go-find-references (STALE): github.com/lukehoban/go-find-references
```

**Comment by dmitshur** [comment]
Hey, thanks for opening this issue.

> In cases when there are a lot of binaries, the names of some of the stale binaries scroll out of view. While updating these, we have to scroll up, see the name, type it and repeat the process.

If you don't mind sharing which binaries you have (or rename them to mock names), could you post an example of lengthy `binstale` output that you're referring to? It'd be very helpful for me to better understand the issue.

I have a possible future enhancement to binstale that I'm considering, and it may help this issue.

But first I want to understand this problem better, and see if there can be an intermediate solution like grepping for "STALE", etc.

**Comment by kulshekhar** [comment]
This is sort of embarrassing. A `grep STALE` should solve this problem :grimacing:

**Comment by dmitshur** [comment]
I'm glad that this can be resolved with piping and `grep`.

I recently saw https://twitter.com/vmg/status/766648542236639233, which is quite relevant, and I think you'll enjoy @kulshekhar. :)
